# Generated by Django 3.1.3 on 2020-11-15 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warriors', '0002_auto_20201116_0147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='staff',
            new_name='is_staff',
        ),
    ]
