# Generated by Django 3.1.3 on 2020-12-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warriors', '0004_auto_20201122_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isComplete',
            field=models.BooleanField(default=False),
        ),
    ]
