# Generated by Django 3.1.3 on 2020-12-10 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warriors', '0005_user_iscomplete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poet', models.CharField(max_length=200)),
                ('beyt_numbers', models.IntegerField()),
                ('create_data', models.DateField(auto_now_add=True)),
                ('ghaleb', models.CharField(max_length=50)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
                ('like_number', models.IntegerField(default=0)),
                ('dislike_number', models.IntegerField(default=0)),
                ('create_data', models.DateField(auto_now_add=True)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warriors.poem')),
            ],
        ),
        migrations.CreateModel(
            name='Beyt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
                ('isKing', models.BooleanField(default=False)),
                ('number_of_beyt', models.IntegerField()),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warriors.poem')),
            ],
        ),
    ]
