# Generated by Django 3.1.3 on 2020-12-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warriors', '0006_beyt_comment_poem'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='adlkfja', upload_to='images/'),
            preserve_default=False,
        ),
    ]
