# Generated by Django 3.1.3 on 2020-12-30 00:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warriors', '0009_auto_20201230_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='liked_users',
            field=models.ManyToManyField(related_name='liked_poems', to=settings.AUTH_USER_MODEL),
        ),
    ]
