# Generated by Django 3.1.3 on 2021-01-02 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warriors', '0010_poem_liked_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
                ('start_index', models.IntegerField()),
                ('end_index', models.IntegerField()),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warriors.poem')),
            ],
        ),
    ]
